# Generated by Django 4.1.1 on 2022-11-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0002_remove_orderproduct_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='records',
            field=models.ManyToManyField(through='fast_food.OrderProduct', to='fast_food.product'),
        ),
    ]
