# Generated by Django 4.1.1 on 2022-11-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0003_order_records'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='records',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_id',
            new_name='product',
        ),
    ]
