# Generated by Django 4.1.1 on 2022-11-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0004_rename_records_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
