# Generated by Django 4.1.1 on 2022-11-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0005_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='fast_food.OrderProduct', to='fast_food.product'),
        ),
    ]
