# Generated by Django 4.1.1 on 2022-11-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0006_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEw'), ('PROCESS', 'PROCESS'), ('DONE', 'DONE')], default='New', max_length=200),
        ),
    ]
