# Generated by Django 4.1.1 on 2022-11-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PROCESS', 'PROCESS'), ('DONE', 'DONE')], default='NEW', max_length=200),
        ),
    ]
