# Generated by Django 4.1.1 on 2022-12-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0010_orderproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='image',
        ),
    ]
