# Generated by Django 4.1.1 on 2022-12-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0012_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
